config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/questions", to: 'pages#questions'
  get "/next_book", to: 'pages#roulette'
  get "/last_suggestion", to: 'suggestions#last_suggestion'

  resources :suggestions, only: [:index, :show, :create]

  resource :profile, only: :show

  resources :books, only: [:show] do
    resources :favorites, only: [:create]
  end
  resources :favorites, only: [:destroy]
  resources :favorites, only: [:index] do
    member do
      patch :mark_as_read
      patch :mark_as_unread
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :suggestions
  has_many :favorites

  validates :title, presence: true
  validates :author, presence: true
  validates :number_of_pages, numericality: { only_integer: true }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  validates :name, presence: true
  validates :mood, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :book_id, presence: true
  validates :user_id, presence: true
  validates :read, inclusion: { in: [true, false] }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books

  validates :name, presence: true
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :book_id, presence: true
  validates :user_id, presence: true

  def self.dates_for_current_user(current_user)
    where(user_id: current_user.id)          # Filter by current user's ID
      .pluck(:created_at)                    # Pluck the 'created_at' column
      .map(&:to_date)                        # Convert datetime to date
      .uniq                                 # Remove duplicate dates
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites
  has_many :suggestions
  has_many :books, through: :favorites
  has_one_attached :photo
  # has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  def has_favorite?(book)
    favorites.exists?(book_id: book.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :email, :phone_number, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :email, :phone_number, :photo])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:mark_as_read, :mark_as_unread, :destroy]

  def create
    @favorite = Favorite.new
    @favorite.user = current_user
    @favorite.book = Book.find(params[:book_id])
    @favorite.save
  end

  def index
    @favorites = Favorite.where(user: current_user)
  end


  def mark_as_read
    @favorite.update(read: true)
    redirect_to favorites_path(anchor: 'justified-tabpanel-0'), notice: 'The book has been marked as read.'
  end

  def mark_as_unread
    @favorite.update(read: false)
    redirect_to favorites_path(anchor: 'justified-tabpanel-1'), notice: 'The book has been marked as unread.'
  end

  def destroy
    @favorite.destroy
    redirect_to favorites_path
  end

  private

  def set_favorite
    @favorite = Favorite.find(params[:id])
  end

  def favorite_params
    params.require(:favorite).permit(:read)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @book = Book.first
  end

  def questions

  end

  def roulette
    @favorite_books = []
    current_user.favorites.where(read: false).each do |favorite|
      @favorite_books << favorite.book
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @suggestions = current_user.suggestions
    @books_read = current_user.favorites.where(read: true)
    @pages_read = current_user.favorites.where(read: true).includes(:book).sum { |favorite| favorite.book.number_of_pages }
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  def index
    @suggestion_dates = Suggestion.dates_for_current_user(current_user).to_json
    @books = Book.all

    if params[:mood].present?
      @books = @books.joins(:category).where("categories.mood ILIKE ?", params[:mood])
    end

    if params[:pages].present?
      case params[:pages].downcase
      when 'short'
        @books = @books.where('number_of_pages < ?', 250)
      when 'medium'
        @books = @books.where('number_of_pages >= ? AND number_of_pages <= ?', 250, 400)
      when 'big'
        @books = @books.where('number_of_pages > ?', 400)
      when 'anyway'
      end
    end

    if params[:age].present?
      case params[:age].downcase
      when 'old'
        @books = @books.where('publishing_date < ?', Date.new(2010))
      when 'recent'
        @books = @books.where('publishing_date >= ?', Date.new(2010))
      end
    end
    @book = @books.sample
    Suggestion.create(user: current_user, book: @book)
  end

  # def suggestion_already_created_today?
  #   current_user.suggestions.where("created_at >= ?", Time.zone.now.beginning_of_day).exists?
  # end

  def add_to_favorites
    @suggestion = Suggestion.find(params[:id])
    current_user.favorites << @suggestion
    redirect_to @suggestion, notice: 'Suggestion was successfully added to favorites.'
  end

  def last_suggestion
    @suggestion = Suggestion.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
 end

app/views/books/show.html.erb
<% if params[:return_to_history] %>
  <div class="m-3">
    <%= link_to profile_path(anchor: 'history'), data: { turbo: false }, class: 'btn btn-secondary', style: 'background-color: #F5C518; color: black' do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
  </div>
<% end %>

<% if params[:return_to_favorites] %>
  <div class="m-3">
    <%= link_to favorites_path(anchor: 'justified-tabpanel-0'), data: { turbo: false }, class: 'btn btn-secondary', style: 'background-color: #F5C518; color: black' do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
  </div>
<% end %>

<% if params[:return_to_next_book] %>
  <div class="m-3">
    <%= link_to next_book_path, data: { turbo: false }, class: 'btn btn-secondary', style: 'background-color: #F5C518; color: black' do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
  </div>
<% end %>



<div class="card mb-3 rounded-3 mx-auto" style="max-width: 600px; background-color: white;">
  <div class="row g-0 mt-5">
    <div class="col-12 text-center">
      <img class="img-fluid rounded-start" src="<%= @book.thumbnail %>" alt="Book Picture" id="img-book" style="width: 50%; max-width: 300px;">
    </div>
  </div>

  <div class="row g-0 mt-3">
    <div class="col-12">
      <div class="card-body">
        <!-- Part 1: Book Title and Author -->
        <div class="p-3 mb-3" style="border-radius: 15px; border: 1px solid #343a40; background-color: #f8f9fa;">
          <h4><strong><%= @book.title %></strong></h4>
          <p><em><%= @book.author %></em></p>
        </div>

        <!-- Accordion for Book Details -->
        <div class="accordion" id="accordionBookDetails">
          <!-- Part 2: About the Book -->
          <div class="accordion-item mb-3" style="border-radius: 10px; overflow: hidden; border: 1px solid #dee2e6; background-color: #f8f9fa;">
            <h2 class="accordion-header" id="headingAbout">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAbout" aria-expanded="false" aria-controls="collapseAbout"
                      style="border-radius: 10px; margin-bottom: 0; border: none; background-color: #f8f9fa;">
                About
              </button>
            </h2>
            <div id="collapseAbout" class="accordion-collapse collapse" aria-labelledby="headingAbout">
              <div class="accordion-body p-3" style="border-radius: 10px; background-color: #ffffff;">
                <div><i class="fa-solid fa-pen-nib"></i> : <%= @book.author %></div>
                <hr style="border: 1px solid black;">
                <div><i class="fa-solid fa-book"></i> : <%= @book.title %></div>
                <hr style="border: 1px solid black;">
                <div><i class="fa-solid fa-copy"></i> : <%= @book.number_of_pages %> pages</div>
                <hr style="border: 1px solid black;">
                <div><i class="fa-solid fa-calendar-days"></i> : <%= @book.publishing_date %></div>
              </div>
            </div>
          </div>

          <!-- Part 3: Description of the Book -->
          <div class="accordion-item mb-3" style="border-radius: 10px; overflow: hidden; border: 1px solid #dee2e6; background-color: #f8f9fa;">
            <h2 class="accordion-header" id="headingDescription">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseDescription" aria-expanded="false" aria-controls="collapseDescription"
                      style="border-radius: 10px; margin-bottom: 0; border: none; background-color: #f8f9fa;">
                Description
              </button>
            </h2>
            <div id="collapseDescription" class="accordion-collapse collapse" aria-labelledby="headingDescription">
              <div class="accordion-body p-3" style="border-radius: 10px; background-color: #ffffff;">
                <p><%= @book.description %></p>
              </div>
            </div>
          </div>
        </div>

        <!-- Buttons Side by Side -->
        <div class="d-flex justify-content-center mt-4" style="gap: 10px;">

        <!-- Add to Favorites Button -->
        <% if current_user.has_favorite?(@book) %>
          <button disabled class="btn btn-info d-flex align-items-center justify-content-center rounded-pill" style="height: 60px; padding: 0 1rem; width: 100%; max-width: 200px; pointer-events: none">
            <i class="fa-regular fa-circle-check" style="font-size: 1.5rem;" id="favorite-icon"></i>
            <span style="margin-left: 0.5rem;">Added</span>
          </button>
        <% else %>
          <%= link_to book_favorites_path(@book), data: { turbo_method: 'POST' }, class: 'btn btn-info d-flex align-items-center justify-content-center rounded-pill', style: 'height: 60px; padding: 0 1rem; width: 100%; max-width: 200px;', id: 'favorite-button' do %>
            <i class="fa-regular fa-bookmark" style="font-size: 1.5rem;" id="favorite-icon"></i>
            <span style="margin-left: 0.5rem;">Add to Favorites</span>
          <% end %>
        <% end %>

        <script>
          document.addEventListener('turbo:submit-end', function(event) {
            const button = document.getElementById('favorite-button');
            if (button) {
              button.querySelector('span').textContent = 'Added';

              const icon = button.querySelector('#favorite-icon');
              icon.classList.remove('fa-bookmark'); // Remove the bookmark icon class
              icon.classList.add('fa-circle-check'); // Add the check icon classes

              button.classList.add('disabled');

              button.style.pointerEvents = 'none';
            }
          });
        </script>

          <!-- Share Button -->
          <button class='btn btn-success d-flex align-items-center justify-content-center rounded-pill' style='height: 60px; padding: 0 1rem; width: 100%; max-width: 200px;' data-bs-toggle="modal" data-bs-target="#shareModal">
            <i class="fa-solid fa-arrow-up-right-from-square fa-lg" style="font-size: 1.5rem;"></i>
            <span style="text-align: center; margin-left: 1rem;">Share</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Share Modal -->
<div class="modal fade" id="shareModal" tabindex="-1" aria-labelledby="shareModalLabel" aria-hidden="true">
  <div class="modal-dialog d-flex align-items-center" style="height: 100vh; width: 100%vw">
    <div class="modal-content">
      <div class="modal-header bg-primary">
        <h5 class="modal-title text-black" id="shareModalLabel">Share this book !</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="d-flex justify-content-around">
          <%= link_to "#", class: "navbar-brand p-0 m-0" do %>
            <div class="d-flex flex-column align-items-center logo-container">
              <i class="fa-regular fa-message text-black fs-1"></i>
              <div class="logo-caption text-black mt-2">Message</div>
            </div>
          <% end %>
          <%= link_to "#", class: "navbar-brand p-0 m-0" do %>
            <div class="d-flex flex-column align-items-center logo-container">
              <i class="fa-brands fa-whatsapp text-black fs-1"></i>
              <div class="logo-caption text-black mt-2">WhatsApp</div>
            </div>
          <% end %>
          <%= link_to "#", class: "navbar-brand p-0 m-0" do %>
            <div class="d-flex flex-column align-items-center logo-container">
              <i class="fa-brands fa-instagram text-black fs-1"></i>
              <div class="logo-caption text-black mt-2">Instagram</div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_fav_button.html.erb
      <div class="d-flex">
        <div class="d-flex justify-content-center align-items-center">
          <%= link_to favorite_path(favorite), data: {turbo_method: 'DELETE'}, class: 'btn btn-success rounded-circle d-flex justify-content-center align-items-center m-2', style: 'height: 45px; width: 45px;' do %>
            <i class="fa-regular fa-bookmark fa-xl"></i>
          <% end %>
          <p class="mt-3">Remove from favorites</p>
        </div>
        <%# <%@favorite.create %>
      </div>

      <div class="d-flex">
  <div class="d-flex justify-content-center align-items-center">
    <%= link_to book_path(book, return_to_favorites: true), class: 'btn btn-success rounded-circle d-flex justify-content-center align-items-center m-2', style: 'height: 45px; width: 45px;' do %>
      <i class="fa-regular fa-eye fa-lg"></i>
    <% end %>
    <p class="mt-3">See more details</p>
  </div>
</div>

app/views/favorites/_favorite_card.html.erb
<link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

<div class="card m-3" style="max-width: 600px; border-radius: 20px">
  <div class="row g-0">

    <div class="col-4 d-flex justify-content-center align-items-center">
  <%= link_to book_path(favorite.book, return_to_favorites: true) do %>
    <img class="img-fluid" src="<%= favorite.book.thumbnail %>" alt="Book Picture" id="img-book" style="height: 160px; display: flex; justify-content: center; align-items: center; overflow: hidden; border-radius: 10px;">
  <% end %>
</div>



    <div class="col-8">
      <div class="card-body p-2">
        <div class="position-relative">
          <button class="btn btn-light position-absolute top-0 end-0 mt-2 me-2" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-ellipsis-v"></i>
          </button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton" style="width: 70vw; background-color: #f5f5f5">
            <li class="m-2">
            <div class="d-flex">
              <%= render "shared/popupshare", id: favorite.id %>
              <p class="mt-2 ps-1">Share this book</p>
              </div>
            </li>
            <li>
              <%= render "favorites/fav_button", favorite: favorite, book: favorite.book %>
            </li>
            <li id="test">
              <% if favorite.read %>
                <%= button_to 'Remove from Read', mark_as_unread_favorite_path(favorite), method: :patch, data: { turbo: false }, class: "dropdown-item", id: "remove-from-read-button" %>
              <% else %>
                <%= button_to 'Read', mark_as_read_favorite_path(favorite), method: :patch, data: { turbo: false }, class: "dropdown-item", id: "mark-as-read-button" %>
              <% end %>
            </li>
          </ul>
        </div>
        <ul class="list-unstyled mb-0">
          <li><p class="mb-1 text-muted"><i class="favorites-text">Title</i></p> <h3 class="mb-1"><strong><%= favorite.book.title %></strong></h3></li>
          <li><p class="mb-1 text-muted"><i class="favorites-text">Author</i></p> <h3 class="mb-1"><strong><%= favorite.book.author %></strong></h3></li>
          <li><p class="mb-1 text-muted"><i class="favorites-text">Year</i></p> <h3 class="mb-1"><strong><%= favorite.book.publishing_date.year %></strong></h3></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

app/views/favorites/index.html.erb
  <%# <div>
    <h1 class ="text-center">favorites list</H1>
  </div> %>

<% if @favorites.first == nil %>
    <div class="text-center">
      <h2> Your list is empty ! </h2>
      <h4> Add some favorite books </h4>

      <%= image_tag "livre.png", class:"rounded mx-auto d-block", alt:"", width: 200 %>
      <div type="browse" class="btn btn-secondary rounded-pill" style="width: 200px; mt-15" >
        <%= link_to 'add favorites', suggestions_path%>
      </div>
    </div>
<%else%>
    <div class="d-flex justify-content-center p-3 mb-2">
      <h1 class="mt-4 mb-4" style="text-align: center; width: 100%;">
        <span style="border-bottom: 10px solid #F5C518; padding-bottom: 10px;">Favorites</span>
      </h1>
    </div>
    <ul class="nav nav-tabs nav-justified " role="tablist" data-controller="tabs">
    <li class="nav-item " role="presentation">
      <a class="nav-link active " id="justified-tab-0" data-bs-toggle="tab" href="#justified-tabpanel-0" role="tab" aria-controls="justified-tabpanel-0" aria-selected="true" style="color: black;"> To Read</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="justified-tab-1" data-bs-toggle="tab" href="#justified-tabpanel-1" role="tab" aria-controls="justified-tabpanel-1" aria-selected="false" style="color: black;"> Read</a>

    </li>
  </ul>
  <div class="tab-content pt-5 " id="tab-content">
    <div class="tab-pane active" id="justified-tabpanel-0" role="tabpanel" aria-labelledby="justified-tab-0">
      <% @favorites.where(read: false).each do |favorite| %>
        <%= render "favorite_card", favorite: favorite  %>
      <% end %>
    </div>
    <div class="tab-pane" id="justified-tabpanel-1" role="tabpanel" aria-labelledby="justified-tab-1">
      <% @favorites.where(read: true).each do |favorite| %>
        <%= render "favorite_card", favorite: favorite  %>
      <% end %>
    </div>
  </div>
<%end%>

app/views/pages/roulette.html.erb
<div class="d-flex justify-content-center p-3 m-2">
        <h1 class="mt-2 mb-4" style="text-align: center; width: 100%;">
          <span style="border-bottom: 10px solid #F5C518; padding-bottom: 10px;"> Pick-A-Book ! </span>
        </h1>
      </div>
  <div class="d-flex flex-column justify-content-center align-items-center" data-controller="roulette" style="padding-top: 10px;">
    <div class="swiper mySwiper">
      <div class="swiper-wrapper">

        <% 10.times do %>
          <% @favorite_books.shuffle.each do |book| %>

            <%= link_to "", book_path(book, return_to_next_book: true), class: "swiper-slide", style: "background-image: url('#{book.thumbnail}'); background-size: cover;" %>

          <% end %>
        <% end %>

      </div>
    </div>

    <div class="mt-4">
      <button data-action="click->roulette#start" class="btn btn-info d-flex align-items-center justify-content-center rounded-pill" style="height: 60px; padding: 0 1rem; width: 100%; max-width: 200px;">
        <i class="fa-solid fa-shuffle" style="font-size: 1.5rem;"></i>
        <span style="margin-left: 0.5rem;">Start</span>
      </button>
    </div>

  </div>


<style>
    .swiper {
      width: 240px;
      height: 320px;
    }

    .swiper-slide {
      display: flex;
      align-items: center;
      justify-content: center;
      border-radius: 18px;
      font-size: 22px;
      font-weight: bold;
      color: #fff;
    }
</style>

app/views/shared/_navbar.html.erb
<% unless current_page?(root_path) %>
<div class="navbar navbar-expand-sm navbar-lewagon d-flex rounded-pill">
  <div class="container-fluid justify-content-around align-items-center ">

      <% if user_signed_in? %>
        <%= link_to questions_path, class: "navbar-brand p-0 m-0" do %>
          <%# <%= if current_page?(root_path)%>
            <%# <div class ="yellowcolor"> %>
              <div class="d-flex flex-column align-items-center logo-container <%= "yellowcolor" if current_page?(questions_path) %> <%= "yellowcolor" if current_page?(suggestions_path) %>">
                <i class="fa-solid fa-house "></i>
                <div class="logo-caption mt-1">Suggestion</div>
              </div>
            <%# </div> %>
          <% end %>
          <%= link_to favorites_path, class: "navbar-brand p-0 m-0" do %>

            <div class="d-flex flex-column align-items-center logo-container  <%= "yellowcolor" if current_page?(favorites_path) %>">
              <i class="fa-regular fa-bookmark "></i>
              <div class="logo-caption mt-1">Favorites</div>
            </div>
          <% end %>
          <%= link_to next_book_path, class: "navbar-brand p-0 m-0" do %>

            <div class="d-flex flex-column align-items-center logo-container <%= "yellowcolor" if current_page?(next_book_path) %>">
              <i class="fa-solid fa-dice "></i>
              <div class="logo-caption mt-1">Pick</div>
            </div>
          <% end %>
          <%= link_to profile_path, class: "navbar-brand p-0 m-0" do %>

            <div class="d-flex flex-column align-items-center logo-container <%= "yellowcolor" if current_page?(profile_path) %>">
              <i class="fa-regular fa-user "></i>
              <div class="logo-caption mt-1">Profile</div>
            </div>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path, class: "navbar-brand p-0 m-0" do %>
            <div class="d-flex flex-column align-items-center logo-container">
              <i class="fa-regular fa-user text-white "></i>
              <div class="logo-caption text-white mt-1">Sign In</div>
            </div>
          <% end %>
          <%= link_to "#", class: "navbar-brand p-0 m-0" do %>
            <div class="d-flex flex-column align-items-center logo-container">
              <%= image_tag "logo.png"%>
              <div class="logo-caption text-white mt-0.5">Daily</div>
            </div>
          <% end %>
          <%= link_to new_user_registration_path, class: "navbar-brand p-0 m-0" do %>
            <div class="d-flex flex-column align-items-center logo-container">
              <i class="fa-regular fa-user text-white"></i>
              <div class="logo-caption text-white mt-1">Sign Up</div>
            </div>
          <% end %>



      <% end %>
  </div>
</div>
<% end %>

app/views/suggestions/_sugg_button.html.erb
      <%= link_to book_favorites_path(book), data: {turbo_method: 'POST'}, class: 'btn btn-success me-2 rounded-circle d-flex justify-content-center align-items-center', style: 'height: 45px; width: 45px;' do %>
        <i class="fa-regular fa-bookmark fa-xl"></i>
        <%# <%@favorite.create %>
      <% end %>

      <%= link_to book_path(book), class: 'btn btn-success me-1 rounded-circle d-flex justify-content-center align-items-center', style: 'height: 45px; width: 45px;' do %>
<i class="fa-solid fa-magnifying-glass fa-lg"></i>
      <% end %>

app/views/suggestions/index.html.erb
<div>
  <div class="p-4 mb-4 bg-white rounded" style="display: inline-block; text-align: left;">
    <h1 class="mt-4 mb-4" style="text-align: center; width: 100%;">
      <span style="border-bottom: 10px solid #F5C518; padding-bottom: 10px;">Suggestion</span>
    </h1>

    <div class="suggestion-detail p-4 ; bg-white"
         style="display: inline-block; text-align: left; border-radius: 15px; border: 1px solid #343a40; margin-top: 20px;">
      <h5 class="mb-3" style="font-size: 22px;"><i><%= @book.description %></i></h5>
    </div>

    <div class="d-flex justify-content-center mt-4" style="gap: 10px;">

      <!-- Add to Favorites Button -->
    <% if current_user.has_favorite?(@book) %>
      <button disabled class="btn btn-info d-flex align-items-center justify-content-center rounded-pill" style="height: 60px; padding: 0 1rem; width: 100%; max-width: 200px; pointer-events: none">
        <i class="fa-regular fa-circle-check" style="font-size: 1.5rem;" id="favorite-icon"></i>
        <span style="margin-left: 0.5rem;">Added</span>
      </button>
    <% else %>
      <%= link_to book_favorites_path(@book), data: { turbo_method: 'POST' }, class: 'btn btn-info d-flex align-items-center justify-content-center rounded-pill', style: 'height: 60px; padding: 0 1rem; width: 100%; max-width: 200px;', id: 'favorite-button' do %>
        <i class="fa-regular fa-bookmark" style="font-size: 1.5rem;" id="favorite-icon"></i>
        <span style="margin-left: 0.5rem;">Add to Favorites</span>
      <% end %>
    <% end %>

    <script>
      document.addEventListener('turbo:submit-end', function(event) {
        const button = document.getElementById('favorite-button');
        if (button) {
          // Change the text to "Added"
          button.querySelector('span').textContent = 'Added';

          // Change the icon to a checked icon
          const icon = button.querySelector('#favorite-icon');
          icon.classList.remove('fa-bookmark'); // Remove the bookmark icon class
          icon.classList.add('fa-circle-check'); // Add the check icon classes

          // Add the disabled class to grey out the button
          button.classList.add('disabled');

          // Disable further clicks
          button.style.pointerEvents = 'none';
        }
      });
    </script>

      <!-- More Details Button -->
      <%= link_to book_path(@book), class: 'btn btn-success d-flex align-items-center justify-content-center rounded-pill', style: 'height: 60px; padding: 0 1rem; width: 100%; max-width: 200px;' do %>
        <i class="fa-regular fa-eye" style="font-size: 1.5rem;"></i>
        <span style="margin-left: 0.5rem;">More details</span>
      <% end %>
    </div>
  </div>
</div>

app/views/suggestions/last_suggestion.html.erb
<p><%= @suggestion.book.title %></p>